const BYTES_IN_A_MEGABYTE = 1_048_576;
export const MAX_UPLOAD_SIZE_MEGABYTES = 5;
const MULTIPART_OVERHEAD_MEGABYTES = 1;

export const MAX_UPLOAD_SIZE = `${MAX_UPLOAD_SIZE_MEGABYTES}m` as const;

export const MAX_REQUEST_BODY_SIZE_BYTES =
  (MAX_UPLOAD_SIZE_MEGABYTES + MULTIPART_OVERHEAD_MEGABYTES) * BYTES_IN_A_MEGABYTE;
