// @generated by bun-sqlgen — do not edit.
// Run the generator to refresh.

/** Result of query `CreateFile`. */
export interface ICreateFileResult {
}

/** Result of query `ListUserFiles`. */
export interface IListUserFilesResult {
    id: IFileColumns["id"];
    user_id: IFileColumns["user_id"];
    name: IFileColumns["name"];
    size: IFileColumns["size"];
    content_type: IFileColumns["content_type"];
    storage_key: IFileColumns["storage_key"];
    created_at: IFileColumns["created_at"];
}

/** Result of query `FindUserFile`. */
export interface IFindUserFileResult {
    id: IFileColumns["id"];
    user_id: IFileColumns["user_id"];
    name: IFileColumns["name"];
    size: IFileColumns["size"];
    content_type: IFileColumns["content_type"];
    storage_key: IFileColumns["storage_key"];
    created_at: IFileColumns["created_at"];
}

/** Result of query `DeleteUserFile`. */
export interface IDeleteUserFileResult {
    storage_key: IFileColumns["storage_key"];
}

export interface Queries {
    CreateFile: ICreateFileResult;
    ListUserFiles: IListUserFilesResult;
    FindUserFile: IFindUserFileResult;
    DeleteUserFile: IDeleteUserFileResult;
}

/** Columns of `auth_account`. */
export interface IAuthAccountColumns {
    id: string;
    issuer: string;
    accountId: string;
    providerId: string;
    userId: string;
    accessToken: string | null;
    refreshToken: string | null;
    idToken: string | null;
    accessTokenExpiresAt: string | null;
    refreshTokenExpiresAt: string | null;
    scope: string | null;
    password: string | null;
    createdAt: string;
    updatedAt: string;
}

/** Schema of `auth_account`. */
export interface IAuthAccountTable {
    columns: IAuthAccountColumns;
    relationType: (typeof schema)["auth_account"]["_relationType"];
    indexes: keyof (typeof schema)["auth_account"]["_indexes"];
    constraints: keyof (typeof schema)["auth_account"]["_constraints"];
}

/** Columns of `auth_session`. */
export interface IAuthSessionColumns {
    id: string;
    expiresAt: string;
    token: string;
    createdAt: string;
    updatedAt: string;
    ipAddress: string | null;
    userAgent: string | null;
    userId: string;
}

/** Schema of `auth_session`. */
export interface IAuthSessionTable {
    columns: IAuthSessionColumns;
    relationType: (typeof schema)["auth_session"]["_relationType"];
    indexes: keyof (typeof schema)["auth_session"]["_indexes"];
    constraints: keyof (typeof schema)["auth_session"]["_constraints"];
}

/** Columns of `auth_user`. */
export interface IAuthUserColumns {
    id: string;
    name: string;
    email: string;
    emailVerified: number;
    image: string | null;
    createdAt: string;
    updatedAt: string;
}

/** Schema of `auth_user`. */
export interface IAuthUserTable {
    columns: IAuthUserColumns;
    relationType: (typeof schema)["auth_user"]["_relationType"];
    indexes: keyof (typeof schema)["auth_user"]["_indexes"];
    constraints: keyof (typeof schema)["auth_user"]["_constraints"];
}

/** Columns of `auth_verification`. */
export interface IAuthVerificationColumns {
    id: string;
    identifier: string;
    value: string;
    expiresAt: string;
    createdAt: string;
    updatedAt: string;
}

/** Schema of `auth_verification`. */
export interface IAuthVerificationTable {
    columns: IAuthVerificationColumns;
    relationType: (typeof schema)["auth_verification"]["_relationType"];
    indexes: keyof (typeof schema)["auth_verification"]["_indexes"];
    constraints: keyof (typeof schema)["auth_verification"]["_constraints"];
}

/** Columns of `file`. */
export interface IFileColumns {
    id: string;
    user_id: string;
    name: string;
    size: number;
    content_type: string;
    storage_key: string;
    created_at: string;
}

/** Schema of `file`. */
export interface IFileTable {
    columns: IFileColumns;
    relationType: (typeof schema)["file"]["_relationType"];
    indexes: keyof (typeof schema)["file"]["_indexes"];
    constraints: keyof (typeof schema)["file"]["_constraints"];
}

export const schema = {
    auth_account: {
        _relationName: "auth_account",
        _relationType: "table",
        _columns: {
            id: { _columnName: "id", _foreignKeys: {} },
            issuer: { _columnName: "issuer", _foreignKeys: {} },
            accountId: { _columnName: "accountId", _foreignKeys: {} },
            providerId: { _columnName: "providerId", _foreignKeys: {} },
            userId: { _columnName: "userId", _foreignKeys: {} },
            accessToken: { _columnName: "accessToken", _foreignKeys: {} },
            refreshToken: { _columnName: "refreshToken", _foreignKeys: {} },
            idToken: { _columnName: "idToken", _foreignKeys: {} },
            accessTokenExpiresAt: { _columnName: "accessTokenExpiresAt", _foreignKeys: {} },
            refreshTokenExpiresAt: { _columnName: "refreshTokenExpiresAt", _foreignKeys: {} },
            scope: { _columnName: "scope", _foreignKeys: {} },
            password: { _columnName: "password", _foreignKeys: {} },
            createdAt: { _columnName: "createdAt", _foreignKeys: {} },
            updatedAt: { _columnName: "updatedAt", _foreignKeys: {} }
        },
        _indexes: {
            auth_account_issuer_accountId_uidx: { _indexName: "auth_account_issuer_accountId_uidx" },
            auth_account_userId_idx: { _indexName: "auth_account_userId_idx" },
            sqlite_autoindex_auth_account_1: { _indexName: "sqlite_autoindex_auth_account_1" }
        },
        _constraints: {}
    },
    auth_session: {
        _relationName: "auth_session",
        _relationType: "table",
        _columns: {
            id: { _columnName: "id", _foreignKeys: {} },
            expiresAt: { _columnName: "expiresAt", _foreignKeys: {} },
            token: { _columnName: "token", _foreignKeys: {} },
            createdAt: { _columnName: "createdAt", _foreignKeys: {} },
            updatedAt: { _columnName: "updatedAt", _foreignKeys: {} },
            ipAddress: { _columnName: "ipAddress", _foreignKeys: {} },
            userAgent: { _columnName: "userAgent", _foreignKeys: {} },
            userId: { _columnName: "userId", _foreignKeys: {} }
        },
        _indexes: {
            auth_session_userId_idx: { _indexName: "auth_session_userId_idx" },
            sqlite_autoindex_auth_session_1: { _indexName: "sqlite_autoindex_auth_session_1" },
            sqlite_autoindex_auth_session_2: { _indexName: "sqlite_autoindex_auth_session_2" }
        },
        _constraints: {}
    },
    auth_user: {
        _relationName: "auth_user",
        _relationType: "table",
        _columns: {
            id: { _columnName: "id", _foreignKeys: {} },
            name: { _columnName: "name", _foreignKeys: {} },
            email: { _columnName: "email", _foreignKeys: {} },
            emailVerified: { _columnName: "emailVerified", _foreignKeys: {} },
            image: { _columnName: "image", _foreignKeys: {} },
            createdAt: { _columnName: "createdAt", _foreignKeys: {} },
            updatedAt: { _columnName: "updatedAt", _foreignKeys: {} }
        },
        _indexes: {
            sqlite_autoindex_auth_user_1: { _indexName: "sqlite_autoindex_auth_user_1" },
            sqlite_autoindex_auth_user_2: { _indexName: "sqlite_autoindex_auth_user_2" }
        },
        _constraints: {}
    },
    auth_verification: {
        _relationName: "auth_verification",
        _relationType: "table",
        _columns: {
            id: { _columnName: "id", _foreignKeys: {} },
            identifier: { _columnName: "identifier", _foreignKeys: {} },
            value: { _columnName: "value", _foreignKeys: {} },
            expiresAt: { _columnName: "expiresAt", _foreignKeys: {} },
            createdAt: { _columnName: "createdAt", _foreignKeys: {} },
            updatedAt: { _columnName: "updatedAt", _foreignKeys: {} }
        },
        _indexes: {
            auth_verification_identifier_idx: { _indexName: "auth_verification_identifier_idx" },
            sqlite_autoindex_auth_verification_1: { _indexName: "sqlite_autoindex_auth_verification_1" }
        },
        _constraints: {}
    },
    file: {
        _relationName: "file",
        _relationType: "table",
        _columns: {
            id: { _columnName: "id", _foreignKeys: {} },
            user_id: { _columnName: "user_id", _foreignKeys: {} },
            name: { _columnName: "name", _foreignKeys: {} },
            size: { _columnName: "size", _foreignKeys: {} },
            content_type: { _columnName: "content_type", _foreignKeys: {} },
            storage_key: { _columnName: "storage_key", _foreignKeys: {} },
            created_at: { _columnName: "created_at", _foreignKeys: {} }
        },
        _indexes: {
            file_user_id_idx: { _indexName: "file_user_id_idx" },
            sqlite_autoindex_file_1: { _indexName: "sqlite_autoindex_file_1" },
            sqlite_autoindex_file_2: { _indexName: "sqlite_autoindex_file_2" }
        },
        _constraints: {}
    }
} as const;

export interface Tables {
    auth_account: IAuthAccountTable;
    auth_session: IAuthSessionTable;
    auth_user: IAuthUserTable;
    auth_verification: IAuthVerificationTable;
    file: IFileTable;
}

declare module "@ilbertt/bun-sqlgen" {
    interface QueryResults extends Queries {
    }
    interface DatabaseTables extends Tables {
    }
}

export {};
